In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset =[['milk','egg','bread','butter','nutmeg','beans'],
         ['ghee','paneer','nutmeg','egg','beans','bread'],
         ['milk','appel','beans','egg','butter'],
         ['bread','corn','beans','egg'],
         ['beans','egg','butter','nutmeg','onion']]
dataset

[['milk', 'egg', 'bread', 'butter', 'nutmeg', 'beans'],
 ['ghee', 'paneer', 'nutmeg', 'egg', 'beans', 'bread'],
 ['milk', 'appel', 'beans', 'egg', 'butter'],
 ['bread', 'corn', 'beans', 'egg'],
 ['beans', 'egg', 'butter', 'nutmeg', 'onion']]

In [4]:
from mlxtend.preprocessing import TransactionEncoder

In [5]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)

In [7]:
df = pd.DataFrame(te_ary,columns = te.columns_)
df

,appel,beans,bread,butter,corn,egg,ghee,milk,nutmeg,onion,paneer
0,False,True,True,True,False,True,False,True,True,False,False
1,False,True,True,False,False,True,True,False,True,False,True
2,True,True,False,True,False,True,False,True,False,False,False
3,False,True,True,False,True,True,False,False,False,False,False
4,False,True,False,True,False,True,False,False,True,True,False

In [12]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(df, min_support = 0.6,use_colnames = True)
frequent_itemsets

    support              itemsets
0       1.0               (beans)
1       0.6               (bread)
2       0.6              (butter)
3       1.0                 (egg)
4       0.6              (nutmeg)
5       0.6        (beans, bread)
6       0.6       (beans, butter)
7       1.0          (beans, egg)
8       0.6       (beans, nutmeg)
9       0.6          (egg, bread)
10      0.6         (egg, butter)
11      0.6         (nutmeg, egg)
12      0.6   (egg, beans, bread)
13      0.6  (egg, beans, butter)
14      0.6  (beans, nutmeg, egg)

# Association Rule Mining

In [16]:
from mlxtend.frequent_patterns import association_rules
res = association_rules(frequent_itemsets,metric = 'confidence',min_threshold = 0.7)
res

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(bread),(beans),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
1,(butter),(beans),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
2,(beans),(egg),1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0
3,(egg),(beans),1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0
4,(nutmeg),(beans),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
5,(bread),(egg),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
6,(butter),(egg),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
7,(nutmeg),(egg),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
8,"(bread, egg)",(beans),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
9,"(beans, bread)",(egg),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
10,(bread),"(beans, egg)",0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
11,"(egg, butter)",(beans),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
12,"(beans, butter)",(egg),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
13,(butter),"(beans, egg)",0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
14,"(beans, nutmeg)",(egg),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
15,"(nutmeg, egg)",(beans),0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0
16,(nutmeg),"(beans, egg)",0.6,1.0,0.6,1.0,1.0,0.0,inf,0.0

In [17]:
res1 = res[['antecedents','consequents','support','confidence','lift']]
res1

        antecedents   consequents  support  confidence  lift
0           (bread)       (beans)      0.6         1.0   1.0
1          (butter)       (beans)      0.6         1.0   1.0
2           (beans)         (egg)      1.0         1.0   1.0
3             (egg)       (beans)      1.0         1.0   1.0
4          (nutmeg)       (beans)      0.6         1.0   1.0
5           (bread)         (egg)      0.6         1.0   1.0
6          (butter)         (egg)      0.6         1.0   1.0
7          (nutmeg)         (egg)      0.6         1.0   1.0
8      (bread, egg)       (beans)      0.6         1.0   1.0
9    (beans, bread)         (egg)      0.6         1.0   1.0
10          (bread)  (beans, egg)      0.6         1.0   1.0
11    (egg, butter)       (beans)      0.6         1.0   1.0
12  (beans, butter)         (egg)      0.6         1.0   1.0
13         (butter)  (beans, egg)      0.6         1.0   1.0
14  (beans, nutmeg)         (egg)      0.6         1.0   1.0
15    (nutmeg, egg)       (beans)      0.6         1.0   1.0
16         (nutmeg)  (beans, egg)      0.6         1.0   1.0

In [19]:
res2 = res1[res1['confidence'] >= 1]
res2

        antecedents   consequents  support  confidence  lift
0           (bread)       (beans)      0.6         1.0   1.0
1          (butter)       (beans)      0.6         1.0   1.0
2           (beans)         (egg)      1.0         1.0   1.0
3             (egg)       (beans)      1.0         1.0   1.0
4          (nutmeg)       (beans)      0.6         1.0   1.0
5           (bread)         (egg)      0.6         1.0   1.0
6          (butter)         (egg)      0.6         1.0   1.0
7          (nutmeg)         (egg)      0.6         1.0   1.0
8      (bread, egg)       (beans)      0.6         1.0   1.0
9    (beans, bread)         (egg)      0.6         1.0   1.0
10          (bread)  (beans, egg)      0.6         1.0   1.0
11    (egg, butter)       (beans)      0.6         1.0   1.0
12  (beans, butter)         (egg)      0.6         1.0   1.0
13         (butter)  (beans, egg)      0.6         1.0   1.0
14  (beans, nutmeg)         (egg)      0.6         1.0   1.0
15    (nutmeg, egg)       (beans)      0.6         1.0   1.0
16         (nutmeg)  (beans, egg)      0.6         1.0   1.0